#!/usr/bin/env bash
# Bash script to update package list and install nginx
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School for the win!" > /var/www/html/index.html
sudo service nginx restart
