#!/usr/bin/env bash
# Bash script to Configure my Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://github.com/kevin-azb permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
